---
    - name: Display OS distribution information
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          Memory: {{ ansible_memtotal_mb }} MB
          Processor: {{ ansible_processor[0] }}

    - name: Download Checkmk-agent vanaf de CMK-server
      ansible.builtin.get_url:
        url: http://192.168.1.6/julianloontjens/check_mk/agents/check-mk-agent_2.3.0p17-1_all.deb
        dest: /tmp/check-mk-agent.deb
        url_username: "{{ cmk_username }}"
        url_password: "{{ cmk_password }}"
        force_basic_auth: yes

    - name: Install agent
      ansible.builtin.apt:
        deb: /tmp/check-mk-agent.deb 
        state: present
        update_cache: yes  

    - name: Register CheckMK agent using Bash
      ansible.builtin.shell: |
        cmk-agent-ctl register --hostname {{ inventory_hostname }} \
          --server 192.168.1.6 --site julianloontjens \
          --user agent_registration --password '{{ cmk_registration_password }}' \
          --trust-cert

    - name: Show inventory hostname and IP
      debug:
        msg: "Host: {{ inventory_hostname }} has IP: {{ ansible_host }}"
      
    - name: Verwijder bestand na installatie
      ansible.builtin.file:
        path: /tmp/check-mk-agent.deb  
        state: absent
      
    - name: Install the Checkmk NGINX plugin
      ansible.builtin.get_url:
        url: http://192.168.1.6/julianloontjens/check_mk/agents/plugins/nginx_status.py
        dest: /usr/lib/check_mk_agent/plugins/check_nginx
        mode: '0755'

    

    - name: Herstart Checkmk-agent
      ansible.builtin.service:
        name: check-mk-agent.socket
        state: restarted

    - name: Ensure NGINX is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes