---
    - name: Display OS distribution information
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          Memory: {{ ansible_memtotal_mb }} MB
          Processor: {{ ansible_processor[0] }}

    - name: Check if a reboot is needed for all servers
      reboot:
        msg: "Reboot initiated by Ansible."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

# Julian Loontjens